INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1113-5', 'Fabricação de malte, cervejas e chopes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1121-6', 'Fabricação de águas envasadas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1122-4', 'Fabricação de refrigerantes e de outras bebidas não alcoólicas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1122-4/01', 'Fabricação de refrigerantes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1122-4/02', 'Fabricação de chá mate e outros chás prontos para consumo');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1411-8/01', 'Confecção de roupas íntimas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1412-6', 'Confecção de peças do vestuário, exceto roupas íntimas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1421-5', 'Fabricação de meias');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1422-3', 'Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('1822-9/01', 'Serviços de encadernação e plastificação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4321-5', 'Instalações elétricas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4330-4', 'Obras de acabamento');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4512-9/02', 'Comércio sob consignação de veículos automotores');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4520-0', 'Manutenção e reparação de veículos automotores');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4530-7', 'Comércio de peças e acessórios para veículos automotores');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4541-2', 'Comércio por atacado e a varejo de motocicletas, peças e acessórios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4542-1/02', 'Comércio sob consignação de motocicletas e motonetas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4543-9', 'Manutenção e reparação de motocicletas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4712-1', 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4713-0', 'Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4721-1', 'Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4722-9', 'Comércio varejista de carnes e pescados - açougues e peixarias');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4723-7', 'Comércio varejista de bebidas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4724-5', 'Comércio varejista de hortifrutigranjeiros');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4729-6', 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4729-6/01', 'Tabacaria');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4729-6/02', 'Comércio varejista de mercadorias em lojas de conveniência');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4729-6/99', 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4731-8', 'Comércio varejista de combustíveis para veículos automotores');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4732-6', 'Comércio varejista de lubrificantes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4741-5', 'Comércio varejista de tintas e materiais para pintura');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4742-3', 'Comércio varejista de material elétrico');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4743-1', 'Comércio varejista de vidros');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4744-0', 'Comércio varejista de ferragens, madeira e materiais de construção');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4751-2', 'Comércio varejista especializado de equipamentos e suprimentos de informática');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4752-1', 'Comércio varejista especializado de equipamentos de telefonia e comunicação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4753-9', 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4754-7', 'Comércio varejista especializado de móveis, colchoaria e artigos de iluminação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4755-5', 'Comércio varejista especializado de tecidos e artigos de cama, mesa e banho');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4756-3', 'Comércio varejista especializado de instrumentos musicais e acessórios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4757-1', 'Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4759-8', 'Comércio varejista de artigos de uso doméstico não especificados anteriormente');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4761-0', 'Comércio varejista de livros, jornais, revistas e papelaria');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4762-8', 'Comércio varejista de discos, CDs, DVDs e fitas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4763-6', 'Comércio varejista de artigos recreativos e esportivos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4771-7', 'Comércio varejista de produtos farmacêuticos para uso humano e veterinário');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4772-5', 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4773-3', 'Comércio varejista de artigos médicos e ortopédicos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4774-1', 'Comércio varejista de artigos de óptica');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4781-4', 'Comércio varejista de artigos do vestuário e acessórios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4782-2', 'Comércio varejista de calçados e artigos de viagem');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4783-1', 'Comércio varejista de jóias e relógios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4785-7', 'Comércio varejista de artigos usados');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4789-0', 'Comércio varejista de outros produtos novos não especificados anteriormente');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('4790-3', 'Comércio ambulante e outros tipos de comércio varejista');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('5510-8', 'Hotéis e similares');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('5611-2', 'Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('5611-2/04', 'Bares e outros estabelecimentos especializados em servir bebidas, sem entretenimento');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('5611-2/05', 'Bares e outros estabelecimentos especializados em servir bebidas, com entretenimento');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6201-5', 'Desenvolvimento de programas de computador sob encomenda');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6201-5/01', 'Desenvolvimento de programas de computador sob encomenda');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6201-5/02', 'Web design');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6202-3', 'Desenvolvimento e licenciamento de programas de computador customizáveis');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6203-1', 'Desenvolvimento e licenciamento de programas de computador não customizáveis');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6204-0', 'Consultoria em tecnologia da informação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6209-1', 'Suporte técnico, manutenção e outros serviços em tecnologia da informação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6311-9', 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na Internet');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6810-2/01', 'Compra e venda de imóveis próprios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6810-2/02', 'Aluguel de imóveis próprios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6810-2/03', 'Loteamento de imóveis próprios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6821-8', 'Intermediação na compra, venda e aluguel de imóveis');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6920-6/01', 'Atividades de contabilidade');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('6920-6/02', 'Atividades de consultoria e auditoria contábil e tributária');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7020-4', 'Atividades de consultoria em gestão empresarial');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7020-4/00', 'Atividades de consultoria em gestão empresarial, exceto consultoria técnica específica');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7111-1', 'Serviços de arquitetura');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7112-0', 'Serviços de engenharia');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7119-7', 'Atividades técnicas relacionadas à arquitetura e engenharia');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7311-4', 'Agências de publicidade');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7312-2', 'Agenciamento de espaços para publicidade, exceto em veículos de comunicação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7420-0/04', 'Filmagem de festas e eventos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7490-1/01', 'Serviços de tradução, interpretação e similares');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7500-1', 'Atividades veterinárias');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('7911-2', 'Agências de viagens');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8011-1', 'Atividades de vigilância e segurança privada');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8030-7', 'Atividades de investigação particular');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8121-4', 'Limpeza em prédios e em domicílios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8130-3', 'Atividades paisagísticas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8211-3', 'Serviços combinados de escritório e apoio administrativo');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8219-9', 'Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8230-0', 'Atividades de organização de eventos, exceto culturais e esportivos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8230-0/02', 'Casas de festas e eventos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8291-1', 'Atividades de cobrança e informações cadastrais');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8299-7/04', 'Leiloeiros independentes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8299-7/06', 'Casas lotéricas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8299-7/07', 'Salas de acesso à Internet');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8299-7/99', 'Outras atividades de serviços prestados principalmente às empresas não especificadas anteriormente');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8511-2', 'Educação infantil - creche');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8512-1', 'Educação infantil - pré-escola');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8513-9', 'Ensino fundamental');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8520-1', 'Ensino médio');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8531-7', 'Educação superior - graduação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8532-5', 'Educação superior - graduação e pós-graduação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8533-3', 'Educação superior - pós-graduação e extensão');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8541-4', 'Educação profissional de nível técnico');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8542-2', 'Educação profissional de nível tecnológico');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8550-3', 'Atividades de apoio à educação');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8591-1', 'Ensino de esportes');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8592-9', 'Ensino de arte e cultura');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8593-7', 'Ensino de idiomas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8599-6/03', 'Treinamento em informática');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8630-5', 'Atividades de atenção ambulatorial executadas por médicos e odontólogos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8630-5/01', 'Atividade médica ambulatorial com recursos para realização de procedimentos cirúrgicos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8630-5/02', 'Atividade médica ambulatorial com recursos para realização de exames complementares');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8630-5/03', 'Atividade médica ambulatorial restrita a consultas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8630-5/04', 'Atividade odontológica');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8711-5/01', 'Clínicas e residências geriátricas');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('8711-5/02', 'Instituições de longa permanência para idosos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('9511-8/00', 'Reparação e manutenção de computadores e de equipamentos periféricos');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('9529-1/02', 'Chaveiros');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('9529-1/03', 'Reparação de relógios');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('9602-5/01', 'Cabeleireiros, manicure e pedicure');
INSERT INTO public."Cnae" ("CodCnae", "DescCnae") VALUES ('9602-5/02', 'Atividades de estética e outros serviços de cuidados com a beleza');
